# Production configuration
replicaCount: 3

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: true

config:
  gcpProjectId: ""
  secretManagerType: "gcp"
  secretName: "url-shortener-secret"
  environment: "production"

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 5m
    memory: 16Mi
